name: TradePlugin
version: 1.0
description: This plugin adds a safe trade system.
author: davehuntcode 
website: https://github.com/davehuntcode/PlayerTrade

main: com.playertrade.TradePlugin

commands:
  playertrade:
    description: PlayerTrade command
    aliases: ['pt']
    
permissions:
  playertrade.*:
    description: Access to everything related to the PlayerTrade plugin.
    children:
      playertrade.trade: true
      playertrade.request: true
      playertrade.accept: true
   
  tradeplugin.perm.request:
    description: Access to the /playertrade request <name> command.
    default: op
  tradeplugin.perm.accept:
    description: Access to the /playertrade accept <name|empty> command to accept a trade request.
    default: op

   