name: TradePlugin
version: 1.0
description: This plugin adds a safe trade system.
author: davehuntcode 
website: https://github.com/davehuntcode/PlayerTrade

main: com.playertrade.TradePlugin

commands:
  playertrade:
    description: PlayerTrade command
    aliases: ['pt']
    
permissions:
  playertrade.*:
    description: Access to everything related to the PlayerTrade plugin.
    children:
      playertrade.trade: true
      playertrade.request: true
      playertrade.accept: true
   
  tradeplugin.perm.trade:
    description: Access to the /trade command
    default: op


   